<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7V1EHS3" failures="1" tests="6" name="com.apex.api.cutomer.gson.poi.test.CustomerGetCustListTest" time="3.609" errors="0" timestamp="2021-10-22T12:01:28 PDT" skipped="0">
  <testcase classname="com.apex.api.cutomer.gson.poi.test.CustomerGetCustListTest" name="testGetUserWithBlank" time="0.002"/>
  <system-out/>
  <testcase classname="com.apex.api.cutomer.gson.poi.test.CustomerGetCustListTest" name="testGetUserWithNonNumber" time="2.444">
    <failure message="Status message not matched expected [NOT Found] but found [Not Found]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status message not matched expected [NOT Found] but found [Not Found]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.apex.api.test.core.ApexHttpValidator.validateStatusCodeReasonPhrase(ApexHttpValidator.java:16)
at com.apex.api.cutomer.gson.poi.test.CustomerGetCustListTest.testGetUserWithNonNumber(CustomerGetCustListTest.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testGetUserWithNonNumber -->
  <system-out/>
  <testcase classname="com.apex.api.cutomer.gson.poi.test.CustomerGetCustListTest" name="testGetUserWithSuccessData" time="0.314"/>
  <system-out/>
  <testcase classname="com.apex.api.cutomer.gson.poi.test.CustomerGetCustListTest" name="testGetForExposedEndpoint" time="0.020"/>
  <system-out/>
  <testcase classname="com.apex.api.cutomer.gson.poi.test.CustomerGetCustListTest" name="testGetUserWithSuccessData" time="0.434"/>
  <system-out/>
  <testcase classname="com.apex.api.cutomer.gson.poi.test.CustomerGetCustListTest" name="testGetUserWithSuccessData" time="0.395"/>
  <system-out/>
</testsuite> <!-- com.apex.api.cutomer.gson.poi.test.CustomerGetCustListTest -->
